### ISSUE TITLE
Missing releasing of resources can cause file handles leaks and locked files on Windows

### ISSUE THREAD

**Issue by centic9** [alx3apps/jgit-buildnumber#16]
A number of objects in JGit require releasing when you are done using it, among them Repository (needs to be released via close()) and RevWalk (should be released via dispose()).

dispose() is probably not absolutely necessary, but still good practice to free resources early. 

Not closing the repository will cause file handles to be still open on Windows, probably causing problems if you e.g. try to remove/move the git repository in a followup Ant task.

**Comment by alx3apps** [comment]
Fixed in 1.2.9
