### ISSUE TITLE
java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.

### ISSUE THREAD

**Issue by dkokic** [alx3apps/jgit-buildnumber#7]
ant script invoked from a custom eclipse builder:

<project name="Mo's Custom Ant Tasks" basedir="." default="git-revision">

```
<description>
    simple example build file
</description>

<path id="custom.classpath">
    <path path="${eclipse.home}/plugins/org.eclipse.jgit_2.1.0.201209190230-r.jar" />
    <path location="jgit-buildnumber-ant-task-1.2.5.jar" />
</path>

<property name="git.repositoryDirectory" value="${ant.home}/../.." />

<target name="git-revision">

    <echo>Here we go ...</echo>

    <taskdef name="jgit-buildnumber" classname="ru.concerteza.util.buildnumber.JGitBuildNumberAntTask" classpathref="custom.classpath" />

    <jgit-buildnumber />

    <echo>Git version extracted ${git.commitsCount} (${git.shortRevision})</echo>
</target>
```

</project>

The mentioned exception is noted in JGit project, but should have been fixed long time ago.

**Comment by gnh1201** [comment]
Additional Information:

Article: Gradle troubleshooting: One of setGitDir or setWorkTree must be called (grgit)

https://gnh1201.wordpress.com/2017/03/23/gradle-troubleshooting-one-of-setgitdir-or-setworktree-must-be-called-grgit/
